name: PR Checker

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: yarn, yarn test
      run: |
        yarn
        yarn test
      env:
        CI: true
